---
title: Serie osservate vs Serie ricostruite (scala log)
author: Guido
date: "`r lubridate::today()`"
---

Sono state selezionate a caso dieci centraline. Le linee in rosso sono le serie ricostruite, mentre quelle in nero sono le serie osservati. I valori sono in scala logaritmica.

```{r intro,include=FALSE,warning=FALSE,message=FALSE,echo=FALSE}
rm(list=objects())
library("tidyverse")
library("git2rdata")
library("latex2exp")

asseY<-TeX("$PM_{10}$ $(\\mu g/m^3)$")

read_vc(root="risultati_modello_lmm_2018/data/",file="pm10_dati_con_predittori2_2018_04agosto2020")->dati
unique(dati$id_centralina)->ID_CENTRALINA
sample(ID_CENTRALINA,size = 12)->CAMPIONE

list.files(pattern="^.+\\.RDS",path="../modello_lmm/",full.names = TRUE)->ffile
```

```{r grafici,warning=FALSE,echo=FALSE,include=FALSE,fig.width=12,fig.height=8}
purrr::map(ffile,.f=function(nomeFile){

str_replace(str_replace_all(nomeFile,"^.+result",""),"\\..+$","")->qualeMese

readRDS(nomeFile)->modello

dati %>%
  filter(mm==qualeMese) %>%
  filter(!is.na(lpm10))->subDati

subDati$lfitted<-fitted(modello)

subDati %>%
  mutate(lfitted=ifelse(is.na(lpm10),NA,lfitted)) %>%
  filter(id_centralina %in% CAMPIONE)->subDati


ggplot(data=subDati,aes(x=yymmdd,y=lpm10))+
  geom_line(aes(group=id_centralina))+
  geom_line(aes(x=yymmdd,y=lfitted,group=id_centralina),colour="firebrick")+
  ylab(asseY)+
  xlab("")+
  facet_wrap(~id_centralina,scales = "free_y")+
  theme_bw()+
  theme(text=element_text(family="Lato"),
        panel.grid = element_blank())->grafico

  grafico

})->listaGrafici
```

### Luglio

```{r,include=TRUE,warning=FALSE,message=FALSE,echo=FALSE,fig.width=12,fig.height=8}
listaGrafici[[4]]
```

### Agosto

```{r,include=TRUE,warning=FALSE,message=FALSE,echo=FALSE,fig.width=12,fig.height=8}
listaGrafici[[5]]
```

### Settembre

```{r,include=TRUE,warning=FALSE,message=FALSE,echo=FALSE,fig.width=12,fig.height=8}
listaGrafici[[6]]
```

### Ottobre

```{r,include=TRUE,warning=FALSE,message=FALSE,echo=FALSE,fig.width=12,fig.height=8}
listaGrafici[[1]]
```

### Novembre

```{r,include=TRUE,warning=FALSE,message=FALSE,echo=FALSE,fig.width=12,fig.height=8}
listaGrafici[[2]]
```

### Dicembre

```{r,include=TRUE,warning=FALSE,message=FALSE,echo=FALSE,fig.width=12,fig.height=8}
listaGrafici[[3]]
```